### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1684]
There is recommendation from [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) **"Ensure text remains visible during webfont load"**
Docs: https://web.dev/font-display/

![image](https://user-images.githubusercontent.com/4050715/96987506-8b0c6b00-153c-11eb-8eec-855045100fb3.png)

Fonts are often large files that take awhile to load. Some browsers hide text until the font loads, causing a [flash of invisible text (FOIT).](https://web.dev/avoid-invisible-text)

### How to avoid showing invisible text

The easiest way to avoid showing invisible text while custom fonts load is to temporarily show a system font. By including `font-display: swap` in your `@font-face` style, you can avoid FOIT in most modern browsers:

```css
@font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2) format('woff2');
  font-display: swap;
}
```
The font-display API specifies how a font is displayed. `swap` tells the browser that text using the font should be displayed immediately using a system font. Once the custom font is ready, it replaces the system font. (See the [Avoid invisible text during loading](https://web.dev/avoid-invisible-text) post for more information.)

### Preload web fonts 
Use `<link rel="preload">` to fetch your font files earlier. Learn more:

- [Preload web fonts to improve loading speed (codelab)](https://web.dev/codelab-preload-web-fonts/)
- [Prevent layout shifting and flashes of invisibile text (FOIT) by preloading optional fonts](https://web.dev/preload-optional-fonts/)

---

Could you implement this in your platform/theme? You already have fonts management functionality. It remains to optimize it a little.
